export const CommonImage = {
    Logo: require("./Logo.png"),
    ShoppingBag: require("./shopping-bag.png"),
    Delete: require("./x.png"),
    Advertise: require("./advertise.png"),
    Dinner: require("./dinner.png"),
    Flash: require("./flash.png"),
    Dish: require("./dish.png"),
    Popup: require("./Union.png"),
    Dish2: require("./dish2.png"),
    Avatar: require("./avatar.png"),
    Star: require("./star.png"),
    User: require("./Subtract.png"),
    Delivery: require("./mdi_truck-fast.png"),
    ColorBag: require("./color-bag.png"),
    Wallet: require("./wallet.png"),
    Setting: require("./settings.png"),
    Languge: require("./language.png"),
    ArrowRight: require("./arrow-right.png"),
    Success: require("./success.png"),
    Fail: require("./fail.png"),
    ArrowLeft: require("./chevron-right.png"),
    CheckedBox: require("./checkedBox.png"),
    UnCheckBox: require("./uncheckBox.png"),
    CheckCircle: require("./check_circle.png"),
    Girl: require("./girl.png"),
    DefaultAvatar: require("./default-avatar.png"),
    Share: require("./share.png"),
    Favourite: require("./favourite.png"),
    Hotline: require("./phone-icon.png"),
    Line: require("./line.png"),
    Location: require("./map.png"),
    Clock: require("./clock.png"),
    ClockGrey: require("./clockGrey.png"),
    Saved: require("./Saved.png"),
    EmptyIcon: require("./Frame.png"),
    CouponBorder: require("./coupon_border.png"),
    CouponBorderBottom: require("./coupon_border1.png"),
    CouponBorderSide: require("./coupon_circle.png"),
    Congratulation: require("./congrat.png"),
    Term: require("./rule.png"),
}
export const InputIcon = {
    Eye: require("./eye.png"),
    EyeOff: require("./eye-off.png"),
    Search: require("./uil_search.png")
}
export const TabsIcon = {
    HomeInactive: require("./home.png"),
    HomeActive: require("./homeActive.png"),
    UserInactive: require("./user.png"),
    UserActive: require("./user_highlight.png"),
    CategoryActive: require("./cateActive.png"),
    CategoryInActive: require("./cateInActive.png"),
    NotiInActive: require("./bell.png"),
    NotiActive: require("./active_bell.png"),
}